import {
  supportedLanguages,
  type AppLanguage,
} from "@/shared/i18n/languages";

export const onboardingNamespace = "onboarding" as const;

type MessageTuple = readonly [string, string, string, string, string, string, string, string, string];
const message = (...values: MessageTuple) => values;

const messages = {
  eyebrow: message("شروع کار", "Getting started", "开始使用", "Primeros pasos", "Начало работы", "Primeiros passos", "Bien démarrer", "Erste Schritte", "はじめに"),
  title: message("چک‌لیست اولین انتشار", "First-publish checklist", "首次发布清单", "Lista para la primera publicación", "Чек-лист первой публикации", "Lista da primeira publicação", "Liste de première publication", "Checkliste für die erste Veröffentlichung", "初回公開チェックリスト"),
  description: message("پیش‌نیازهای عمومی شدن صفحه رزرو را تکمیل کنید. این مسیر چند بخش پنل را کنار هم قرار می‌دهد.", "Complete the prerequisites for a public booking page. This journey coordinates several panel areas.", "完成公开预约页面的前置条件。此流程串联多个面板区域。", "Completa los requisitos de la página pública de reservas. Este recorrido coordina varias áreas.", "Выполните условия для публичной страницы записи. Этот путь объединяет несколько разделов панели.", "Conclua os requisitos da página pública de agendamento. Esta jornada coordena várias áreas.", "Remplissez les prérequis de la page publique de réservation. Ce parcours coordonne plusieurs zones.", "Erfüllen Sie die Voraussetzungen für die öffentliche Buchungsseite. Dieser Ablauf verbindet mehrere Bereiche.", "公開予約ページの前提条件を完了します。この導線は複数の管理領域をつなぎます。"),
  workflowNote: message("شروع کار یک مسیر میان‌بخشی است، نه منبع جداگانه اطلاعات کسب‌وکار.", "Onboarding is a cross-domain journey, not a separate source of business data.", "引导流程是跨域旅程，并非独立的业务数据源。", "La incorporación es un recorrido transversal, no otra fuente de datos.", "Онбординг — сквозной путь, а не отдельный источник бизнес-данных.", "A integração inicial é uma jornada entre domínios, não outra fonte de dados.", "L’intégration est un parcours transversal, pas une source de données distincte.", "Onboarding ist ein bereichsübergreifender Ablauf, keine eigene Geschäftsdatenquelle.", "オンボーディングは横断的な導線で、独立した事業データ源ではありません。"),
  progressLabel: message("پیشرفت الزامی", "Required progress", "必填进度", "Progreso obligatorio", "Обязательный прогресс", "Progresso obrigatório", "Progression requise", "Pflichtfortschritt", "必須項目の進捗"),
  progressText: message("{{complete}} از {{total}} مورد الزامی", "{{complete}} of {{total}} required items", "已完成 {{complete}} / {{total}} 个必填项", "{{complete}} de {{total}} requisitos", "{{complete}} из {{total}} обязательных пунктов", "{{complete}} de {{total}} itens obrigatórios", "{{complete}} sur {{total}} éléments requis", "{{complete}} von {{total}} Pflichtpunkten", "必須 {{total}}件中 {{complete}}件"),
  requiredTitle: message("پیش‌نیازهای انتشار", "Publish prerequisites", "发布前置条件", "Requisitos de publicación", "Условия публикации", "Requisitos de publicação", "Prérequis de publication", "Voraussetzungen zur Veröffentlichung", "公開の前提条件"),
  businessProfile: message("پروفایل کسب‌وکار تکمیل شده است", "Business profile is complete", "企业资料已完成", "El perfil del negocio está completo", "Профиль бизнеса заполнен", "O perfil do negócio está completo", "Le profil de l’entreprise est complet", "Unternehmensprofil ist vollständig", "事業プロフィールが完成している"),
  businessProfileHelp: message("نام، معرفی و اطلاعات عمومی قابل نمایش آماده است.", "Public business identity and description are ready.", "公开的企业名称和介绍已准备好。", "La identidad y descripción públicas están listas.", "Публичное название и описание готовы.", "A identidade e descrição públicas estão prontas.", "L’identité et la description publiques sont prêtes.", "Öffentliche Identität und Beschreibung sind bereit.", "公開する事業情報と説明が準備済みです。"),
  activeService: message("حداقل یک خدمت فعال وجود دارد", "At least one service is active", "至少有一个启用的服务", "Hay al menos un servicio activo", "Есть минимум одна активная услуга", "Há pelo menos um serviço ativo", "Au moins un service est actif", "Mindestens ein Service ist aktiv", "有効なサービスが1件以上ある"),
  activeServiceHelp: message("خدمت قابل رزرو، مدت و قیمت معتبر دارد.", "A bookable service has valid duration and price details.", "可预约服务包含有效的时长和价格。", "Un servicio reservable tiene duración y precio válidos.", "У услуги для записи указаны корректные длительность и цена.", "Um serviço reservável tem duração e preço válidos.", "Un service réservable possède une durée et un prix valides.", "Ein buchbarer Service hat gültige Dauer und Preisangaben.", "予約可能なサービスに有効な所要時間と価格があります。"),
  availability: message("زمان‌های قابل رزرو تنظیم شده است", "Bookable availability is configured", "可预约时间已配置", "La disponibilidad reservable está configurada", "Доступное время настроено", "A disponibilidade está configurada", "Les disponibilités réservables sont configurées", "Buchbare Verfügbarkeit ist eingerichtet", "予約可能時間が設定されている"),
  availabilityHelp: message("ساعت کاری، ظرفیت و استثناها باعث ایجاد زمان معتبر می‌شوند.", "Working hours, capacity, and exceptions produce a valid slot.", "工作时间、容量和例外可生成有效时段。", "Horarios, capacidad y excepciones producen una franja válida.", "Рабочие часы, вместимость и исключения дают доступный слот.", "Horário, capacidade e exceções produzem um horário válido.", "Horaires, capacité et exceptions produisent un créneau valide.", "Arbeitszeiten, Kapazität und Ausnahmen ergeben einen gültigen Termin.", "営業時間・定員・例外から有効な枠が作られます。"),
  bookingPolicy: message("سیاست رزرو مشخص شده است", "Booking policy is configured", "预约策略已配置", "La política de reserva está configurada", "Политика записи настроена", "A política de agendamento está configurada", "La politique de réservation est configurée", "Buchungsrichtlinie ist eingerichtet", "予約ポリシーが設定されている"),
  bookingPolicyHelp: message("حالت تأیید یا فوری و قواعد لغو برای مشتری روشن است.", "Approval or instant mode and cancellation rules are defined.", "审核或即时模式及取消规则已确定。", "El modo de aprobación o instantáneo y las reglas de cancelación están definidos.", "Режим подтверждения или мгновенной записи и правила отмены заданы.", "O modo de aprovação ou imediato e as regras de cancelamento estão definidos.", "Le mode avec validation ou instantané et les règles d’annulation sont définis.", "Bestätigungs- oder Sofortmodus und Stornoregeln sind festgelegt.", "承認制または即時確定とキャンセル規定が定義済みです。"),
  publicPreview: message("پیش‌نمایش عمومی بررسی شده است", "Public-page preview has been reviewed", "公开页面预览已检查", "Se revisó la vista previa pública", "Предпросмотр публичной страницы проверен", "A prévia da página pública foi revisada", "L’aperçu de la page publique a été vérifié", "Vorschau der öffentlichen Seite wurde geprüft", "公開ページのプレビューを確認済み"),
  publicPreviewHelp: message("صفحه در موبایل و دسکتاپ و جهت راست‌به‌چپ بررسی شده است.", "The page has been checked on mobile, desktop, and right-to-left layout.", "页面已在移动端、桌面端和从右到左布局中检查。", "La página se revisó en móvil, escritorio y diseño RTL.", "Страница проверена на мобильном, десктопе и в RTL.", "A página foi verificada em celular, desktop e layout RTL.", "La page a été vérifiée sur mobile, ordinateur et en RTL.", "Die Seite wurde mobil, am Desktop und im RTL-Layout geprüft.", "モバイル・デスクトップ・右から左の表示を確認済みです。"),
  optionalTitle: message("آماده‌سازی اختیاری", "Optional preparation", "可选准备", "Preparación opcional", "Необязательная подготовка", "Preparação opcional", "Préparation facultative", "Optionale Vorbereitung", "任意の準備"),
  teamOptional: message("عضو تیم و خدمت قابل ارائه او تنظیم شده است", "A team member and their bookable services are configured", "团队成员及其可预约服务已配置", "Se configuró un miembro y sus servicios reservables", "Настроены сотрудник и доступные ему услуги", "Um membro da equipe e seus serviços foram configurados", "Un membre de l’équipe et ses services réservables sont configurés", "Teammitglied und buchbare Services sind eingerichtet", "チームメンバーと担当サービスが設定されている"),
  teamOptionalHelp: message("برای کسب‌وکار تک‌نفره لازم نیست و مانع انتشار نمی‌شود.", "Not required for a solo provider and never blocks publishing.", "个人服务商无需此项，且不会阻止发布。", "No es obligatorio para un proveedor individual ni bloquea la publicación.", "Не требуется для одиночного поставщика и не блокирует публикацию.", "Não é obrigatório para prestador individual e não bloqueia a publicação.", "Non requis pour un prestataire seul et ne bloque jamais la publication.", "Für Solo-Anbieter nicht nötig und kein Veröffentlichungshindernis.", "一人事業者には不要で、公開を妨げません。"),
  publish: message("انتشار صفحه رزرو", "Publish booking page", "发布预约页面", "Publicar página de reservas", "Опубликовать страницу записи", "Publicar página de agendamento", "Publier la page de réservation", "Buchungsseite veröffentlichen", "予約ページを公開"),
  blocked: message("برای انتشار، همه موارد الزامی را کامل کنید.", "Complete every required item before publishing.", "请先完成所有必填项再发布。", "Completa todos los requisitos antes de publicar.", "Перед публикацией выполните все обязательные пункты.", "Conclua todos os itens obrigatórios antes de publicar.", "Complétez tous les éléments requis avant de publier.", "Erfüllen Sie vor der Veröffentlichung alle Pflichtpunkte.", "公開前に必須項目をすべて完了してください。"),
  published: message("صفحه رزرو برای انتشار آماده و فعال شد.", "The booking page is ready and marked as published.", "预约页面已准备就绪并标记为已发布。", "La página está lista y marcada como publicada.", "Страница готова и отмечена как опубликованная.", "A página está pronta e marcada como publicada.", "La page est prête et marquée comme publiée.", "Die Buchungsseite ist bereit und als veröffentlicht markiert.", "予約ページの準備が整い、公開済みになりました。"),
} as const;

export type OnboardingMessages = Record<keyof typeof messages, string>;

export const onboardingResources = Object.fromEntries(
  supportedLanguages.map((language, languageIndex) => [
    language,
    Object.fromEntries(Object.entries(messages).map(([key, values]) => [key, values[languageIndex]])),
  ]),
) as Record<AppLanguage, OnboardingMessages>;

export const onboardingI18n = {
  namespace: onboardingNamespace,
  resources: onboardingResources,
} as const;
